export const plantTypes = [
    "Fleur",
    "Arbuste",
    "Légume",
    "Herbe",
    "Arbre",
    "Cactus",
    "Succulente",
    "Vivace",
    "Annuelle",
    "Bulbe",
    "Ornementale",
    "Fruitier",
    "Aromatique",
    "Graine",
    "Plante grimpante",
    "Aquatique",
    "Exotique",
  ];
